version: '3'
services:
  r-analysis:
    build: .
    image: german-credit-analysis
    volumes:
      - ./scripts:/app/scripts  # Add this line to mount the scripts directory
      - ./data:/app/data
      - ./results:/app/results
      - ./reports:/app/reports

    entrypoint: ["Rscript"]
    command: scripts/05_analysis.R
  
  r-interactive:
    build: .
    image: german-credit-analysis
    volumes:
      - ./:/app
    command: R