version: '3'
services:
  r-analysis:
    build: .
    image: german-credit-analysis
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./results:/app/results
      - ./reports:/app/reports
    command: tail -f /dev/null  # This keeps the container running
  
  r-interactive:
    build: .
    image: german-credit-analysis
    volumes:
      - ./:/app
    command: R